GET http://localhost:3001/api/blogs HTTP/1.1

###
GET http://localhost:3001/api/blogs/hello HTTP/1.1

### 
POST http://localhost:3001/api/blogs HTTP/1.1
Content-Type: application/json 

{
    "title": "kill bas",
    "author": "ziv 123",
    "url": "https://www.linkedin.com/in/nadav-vol-46ab67220/",
    "likes": 113,
    "userId": "61b8ba25131122a7616cdbda"
}

### 
POST http://localhost:3001/api/users HTTP/1.1
Content-Type: application/json

{ 
    "name": "shalom asayag",
    "userName": "shalom_asayag",
    "password": "x",
    "blogs": ["Zzzz"]
}

###
GET http://localhost:3001/api/users HTTP/1.1
