GET http://localhost:3003/api/blogs HTTP/1.1
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxYmRiODQ0OTI5MDE2OGU1ZTVmOTM2ZSIsImlhdCI6MTYzOTgyMzQyOH0.zvUqGvvnwR_KYQB1_Pc-fiP1otPcym4ITP8uoROJqB0

# ###
# GET http://localhost:3001/api/blogs/hello HTTP/1.1

# ### 
POST http://localhost:3001/api/blogs HTTP/1.1
Content-Type: application/json 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxYjk5MzlhM2MwZDIzNWIxYTQwN2Y0NCIsImlhdCI6MTYzOTU2Mzg3OH0.bo3FtDtt1hIJxPfNURRIWGMFn-5u2tWoYZ1uODvdHtc

{
    "title": "koola like",
    "author": "ziv 123",
    "url": "https://www.linkedin.com/in/nadav-vol-46ab67220/",
    "userId": "61b8c3c4cbfee92864a731e3"
}
###

PUT /api/blogs/likes HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxYjk5MzlhM2MwZDIzNWIxYTQwN2Y0NCIsImlhdCI6MTYzOTU2Mzg3OH0.bo3FtDtt1hIJxPfNURRIWGMFn-5u2tWoYZ1uODvdHtc

{
    "_id": "5a422bc61b54a676234d17fc", "likes": "141"
}

### 

DELETE http://localhost:3001/api/blogs HTTP/1.1
Content-Type: application/json

{
"_id": "61b8c3c4cbfee92864a731e3"
}

### 
POST http://localhost:3003/api/users HTTP/1.1
Content-Type: application/json

{ 
    "name": "adon_olam2",
    "userName": "adon_olam5",
    "password": "12345",
    "blogs": []
}

###
POST http://localhost:3003/api/login HTTP/1.1
Content-Type: application/json

{ 
    "userName": "adon_olam5",
    "password": "12345"
}


###
GET http://localhost:3001/api/users HTTP/1.1


